[package]
name = "dockerit"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
#winreg = "0.10"
walkdir = "2.5.0"
[dev-dependencies]
tempfile = "3.8"

[[bin]]
name = "dockerit"
path = "src/main.rs"
